CREATE TABLE MOVIES
(
  MOVIEID VARCHAR(10),
  TITLE VARCHAR(150),
  IMDBID VARCHAR(10),
  SPANISHTITLE VARCHAR(150),
  IMDBPICTUREURL VARCHAR(250),
  YEAR NUMBER,
  RTID VARCHAR(150),
  RTALLCRITICSRATING NUMBER,
  RTALLCRITICSNUMREVIEWS NUMBER,
  RTALLCRITICSNUMFRESH NUMBER,
  RTALLCRITICSNUMROTTEN NUMBER,
  RTALLCRITICSSCORE NUMBER,
  RTTOPCRITICSRATING NUMBER,
  RTTOPCRITICSNUMREVIEWS NUMBER,
  RTTOPCRITICSNUMFRESH NUMBER,
  RTTOPCRITICSNUMROTTEN NUMBER,
  RTTOPCRITICSSCORE NUMBER,
  RTTOPRTAUDIENCERATING NUMBER,
  RTAUDIENCENUMRATINGS NUMBER,
  RTAUDIENCESCORE NUMBER,
  RTPICTUREURL VARCHAR(250),
  PRIMARY KEY (MOVIEID)
);


CREATE TABLE GENRES
(
  MOVIEID VARCHAR(10),
  GENRE VARCHAR(50),
  PRIMARY KEY (MOVIEID, GENRE),
  FOREIGN KEY (MOVIEID) REFERENCES MOVIES(MOVIEID) ON DELETE CASCADE
);


CREATE TABLE COUNTRIES
(
  MOVIEID VARCHAR(10),
  COUNTRY VARCHAR(50),
  PRIMARY KEY (MOVIEID),
  FOREIGN KEY (MOVIEID) REFERENCES MOVIES(MOVIEID) ON DELETE CASCADE
);


CREATE TABLE FILMING_COUNTRIES
(
  MOVIEID VARCHAR(10),
  COUNTRY VARCHAR(50),
  PRIMARY KEY (MOVIEID, COUNTRY),
  FOREIGN KEY (MOVIEID) REFERENCES MOVIES(MOVIEID) ON DELETE CASCADE
);


CREATE TABLE TAGS
(
  TAGID VARCHAR(10),
  TAGNAME VARCHAR(50),
  PRIMARY KEY (TAGID)
);


CREATE TABLE MOVIE_TAGS
(
  MOVIEID VARCHAR(10),
  TAGID VARCHAR(10),
  TAGWEIGHT NUMBER,
  PRIMARY KEY (MOVIEID, TAGID),
  FOREIGN KEY (MOVIEID) REFERENCES MOVIES(MOVIEID) ON DELETE CASCADE,
  FOREIGN KEY (TAGID) REFERENCES TAGS(TAGID) ON DELETE CASCADE
);



CREATE INDEX I_YEAR ON MOVIES(YEAR);
CREATE INDEX I_ratings1 ON MOVIES(RTALLCRITICSRATING);
CREATE INDEX I_ratings2 ON MOVIES(RTTOPCRITICSRATING); 
CREATE INDEX I_ratings3 ON MOVIES(RTTOPRTAUDIENCERATING); 
CREATE INDEX I_numReviews1 ON MOVIES(RTTOPCRITICSNUMREVIEWS);
CREATE INDEX I_numReviews2 ON MOVIES(RTALLCRITICSNUMREVIEWS);
CREATE INDEX I_numReviews3 ON MOVIES(RTAUDIENCENUMRATINGS);
CREATE INDEX I_GENRE ON GENRES(GENRE);
CREATE INDEX I_country ON Countries(COUNTRY);
CREATE INDEX I_filming_country ON FILMING_COUNTRIES(COUNTRY);
CREATE INDEX I_tagweight ON MOVIE_TAGS(TAGWEIGHT);
CREATE INDEX I_tagMID ON Movie_Tags(MOVIEID);
CREATE INDEX I_genreMID ON genres(MOVIEID);
