DROP INDEX I_YEAR;
DROP INDEX I_ratings1;
DROP INDEX I_ratings2;
DROP INDEX I_ratings3; 
DROP INDEX I_numReviews1;
DROP INDEX I_numReviews2;
DROP INDEX I_numReviews3;
DROP INDEX I_GENRE;
DROP INDEX I_country;
DROP INDEX I_filming_country;
DROP INDEX I_tagweight;
DROP INDEX I_tagMID;
DROP INDEX I_genreMID;


DROP TABLE GENRES;
DROP TABLE COUNTRIES;
DROP TABLE FILMING_COUNTRIES;
DROP TABLE MOVIE_TAGS;
DROP TABLE TAGS;
DROP TABLE MOVIES;
